## **Fundamentals of PyTorch**

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors

Scalar

In [ ]:
# scalar
scalar = torch.tensor(18)
scalar

tensor(18)

Pytorch tensors are created using `torch.Tensor()`

In [ ]:
# checking the dimenison of scalar = 0 [ number of square bracket ]
print(scalar.shape)
print(scalar.ndim)

torch.Size([])
0


In [ ]:
# get back the scalar from the tensor
scalar.item()

18

Vector

In [ ]:
vector = torch.tensor([3,3,2,2])
vector

tensor([3, 3, 2, 2])

In [ ]:
# dimension of vector = 1 (number of square bracket)
vector.ndim

1

In [ ]:
vector.shape # elements in a vector.

torch.Size([4])

MATRIX

In [ ]:
MATRIX = torch.tensor([[2,3,2,2],[3,2,3,1],[2,4,2,1]])
MATRIX

tensor([[2, 3, 2, 2],
        [3, 2, 3, 1],
        [2, 4, 2, 1]])

In [ ]:
MATRIX.ndim
# number of square brackets

2

In [ ]:
MATRIX.shape

torch.Size([3, 4])

In [ ]:
MATRIX[0][0].item()

2

TENSOR

In [ ]:
TENSOR = torch.tensor([[[2,4,2],[1,2,1],[1,31,1]]])
TENSOR

tensor([[[ 2,  4,  2],
         [ 1,  2,  1],
         [ 1, 31,  1]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [ ]:
 # shape is 1*3*3 --> One 3*3 matrix [ 3 square brackets.]

In [ ]:
TENSOR2 = torch.tensor([[[2,4,2],[1,2,1],[1,31,1]],
                        [[2,4,2],[1,2,1],[1,31,1]]])
TENSOR2

tensor([[[ 2,  4,  2],
         [ 1,  2,  1],
         [ 1, 31,  1]],

        [[ 2,  4,  2],
         [ 1,  2,  1],
         [ 1, 31,  1]]])

In [ ]:
TENSOR2.shape
# Two 3*3 matrix.

torch.Size([2, 3, 3])

### Random tensors

Why Random Tensors?
Random tensors are important because the way the Neural Network learn is that they start with tensors full of random numbers and then adjust them to better represent the data

In [ ]:
# create a random tensor size( 3*2)
rand_tens = torch.rand(3,2)
rand_tens

tensor([[0.7596, 0.9454],
        [0.9966, 0.8929],
        [0.7324, 0.7488]])

In [ ]:
rand_tens.ndim
# = 2 [[2 square brackets ]]

2

In [ ]:
rand_tens = torch.rand(2,2,4)
rand_tens
# one 2*4 matrix

tensor([[[0.9600, 0.6095, 0.4068, 0.8055],
         [0.4641, 0.8179, 0.6979, 0.4893]],

        [[0.2973, 0.2920, 0.0016, 0.0011],
         [0.5666, 0.5275, 0.6513, 0.2440]]])

In [ ]:
rand_tens.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
rand_img_tens = torch.rand(size=(3,224,224)) # color(RGB),height,width
rand_img_tens.shape, rand_img_tens.ndim

(torch.Size([3, 224, 224]), 3)

## Creating random tensors with ```1's``` and ```0's```

In [ ]:
# all zeros
zeros = torch.zeros(size=(2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
 # all ones.
 ones = torch.ones(size=(3,2))
 ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype # DATA type

torch.float32

## Creating a range of tensors and tensors-like

In [ ]:
# torch.arange(start = 0, end = 100, step = 10)
# or simply ~~~ torch.arange(3,2)
one_to_N = torch.arange(start = 1, end = 15, step = 2)
one_to_N

tensor([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
# creating tensors-like (  in same shape )
like_one_to_N = torch.zeros_like(input = one_to_N)
like_one_to_N

tensor([0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# float 32 tensor
float_32_tens = torch.tensor([3.2,4.0,2.],dtype = None)
float_32_tens

tensor([3.2000, 4.0000, 2.0000])

In [ ]:
float_32_tens.dtype # default data type is float 32

torch.float32

In [ ]:
float_32_tens = torch.tensor([3.2,4.0,2.],
                             dtype = None,
                             device = "cpu",
                             requires_grad= False)
float_32_tens
# dtype = float32,float64,float16 or float.half
# device: if we want to run on a specific device
# grad_ : if need to track the gradient to do some computations.

tensor([3.2000, 4.0000, 2.0000])

So 32-bit is normal precision, 16-bit is half precision, and if we need more higher precision 64-bit (double the precision)

In [ ]:
# Common mistakes in Pytorch and deep learning

**Note**: Tensor datatypes is one of the 3 big errors we'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32to16 = float_32_tens.type(torch.float16)
float_32to16

tensor([3.1992, 4.0000, 2.0000], dtype=torch.float16)

In [ ]:
float_32to16*float_32_tens
# here it works: but the error will come in some cases.

tensor([10.2375, 16.0000,  4.0000])

Getting Information from Tensors

In [ ]:
# to solve the 3 major problems:
# 1. some_tensor.dtype
# 2. some_tensor.shape
# 3. some_tensor.device

Manipulating tensors: Tensor Operations

Operations:
1. addition
2. subtraction
3. multiplication (element-wise)
4. div
5. Matrix multiplication (dot product)

In [ ]:
# adding 10 to each tensor.
tensor = torch.tensor([24,2,4])
tensor+10

tensor([34, 12, 14])

In [ ]:
# *10 to each tensor element.
tensor*10

tensor([240,  20,  40])

In [ ]:
tensor/10

tensor([2.4000, 0.2000, 0.4000])

In [ ]:
# Pytorch in-built functions.
torch.mul(tensor,10)

tensor([240,  20,  40])

In [ ]:
# Matrix-Multiplication
tensor*tensor

tensor([576,   4,  16])

In [ ]:
torch.matmul(tensor,tensor)
# it adds all the elements of the product matrix

tensor(596)

In [ ]:
# using %%time we can find which method is less time consuming.(matmul) offcourse.

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.12 ms, sys: 0 ns, total: 1.12 ms
Wall time: 1.14 ms


tensor(596)

To fix the tensor shape issue, we manipulate the shape: use **transpose**
It switches the axes or dimension.

In [ ]:
tensor1 = torch.tensor([[2,4,2],[2,342,2]])
tensor1.T

tensor([[  2,   2],
        [  4, 342],
        [  2,   2]])

In [ ]:
tensor1.shape,tensor1.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

## Tensor Aggregation

In [ ]:
# finding min, max,sum etc.
x = torch.arange(0,100,15)
x

tensor([ 0, 15, 30, 45, 60, 75, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x)

RuntimeError: ignored

In [ ]:
x.dtype

torch.int64

In [ ]:
# we need to change the datatype to float.
torch.mean(x.type(torch.float32))
# mean requires the float datatype

tensor(45.)

In [ ]:
x.sum()

tensor(315)

## Finding the positional min and max

In [ ]:
# gives the position of the required functional value.
x.argmin()

tensor(0)

In [ ]:
x[0] # is the minimum value.

tensor(0)

In [ ]:
x.argmax()

tensor(6)

In [ ]:
x[6] # is the maximum value

tensor(90)

## Reshaping, viewing, stacking, Squeezing, unsqueezing
* Reshaping: reshape the shape to desired
* view: return the view of input tensor.
* stacking: combine the multiple tensors on top of each other(vstack) or side by side ( hstack)
* squeeze: remove all `1` dimensions from a tensor
* unsqueeze: add a `1` dimension from a tensor.
* permute: return a view of the input with dimensions permuted(swapped) in a certain way.

In [ ]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape adds an extra dimension:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# view change the view in which we want to see:
# it share the same memory location: and any change in z would be reflected in x too:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 100
z,x
# first element got changed in both.

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [ ]:
# stack

In [ ]:
# it puts tensors on above another along different axes (0 , 1)
x_stacked = torch.stack([x,x]) # vertical stacking:
x_stacked,x_stacked.shape

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
         [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]),
 torch.Size([2, 9]))

In [ ]:
x_stacked = torch.stack([x,x],dim= 1) # side by side || column wise
x_stacked, x_stacked.shape

(tensor([[100., 100.],
         [  2.,   2.],
         [  3.,   3.],
         [  4.,   4.],
         [  5.,   5.],
         [  6.,   6.],
         [  7.,   7.],
         [  8.,   8.],
         [  9.,   9.]]),
 torch.Size([9, 2]))

In [ ]:
# squeezing: [1,1,1,9]---->[9]

squeezing removes the `1` from the tensors

In [ ]:
x_squeeze = x_reshaped.squeeze()
x_reshaped.shape,x_squeeze,x_squeeze.shape

(torch.Size([1, 9]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 torch.Size([9]))

In [ ]:
x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(torch.Size([1, 9]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 torch.Size([9]))

In [ ]:
# Unsqeeze

In [ ]:
# unsqueeze adds an extra dimension at a specific dim
x_unsqueezed = x_squeeze.unsqueeze(dim = 0)
x_squeeze,x_unsqueezed

(tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]]))

In [ ]:
x_squeeze.shape,x_unsqueezed.shape

(torch.Size([9]), torch.Size([1, 9]))

In [ ]:
# torch.permute -- > rearranges the dimensions of a target tensor in specified order.

In [ ]:
x = torch.rand(224,224,3) # H * W * Color(RGB)
x.shape

torch.Size([224, 224, 3])

In [ ]:
# changing the dimensions:
x_permuted = x.permute(2,0,1) # 0->2, 1->0, 2->1
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
# x and x_permuted share the same memory:
x[0,0,0] = 9999
x[0,0,0],x_permuted[0,0,0]

(tensor(9999.), tensor(9999.))

## Selecting data form tensors: Indexing

In [ ]:
# create a tensor:
x = torch.arange(1,10).reshape(1,3,3) # 9 elements so: one 3*3 matrix:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on our tensor:
x[0] # first tensor of x: 3*3 matrix:

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# let's index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on the most inner bracket(last dim)
x[0][0][0]

tensor(1)

In [ ]:
x[1]
# error: since we have only one 3*3 matrix:
# we could have accessed x[1] if x--> x.shape= N,3,3, N>1

IndexError: ignored

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# Indexing using ":" to select all of the target dimensions:
# all of first dimension, but 0th of second dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# all values of 0,1 dim but index-1 values of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of 0-dim, only 1 of dim-1 and 2.
x[:,1,1]

tensor([5])

In [ ]:

x[0,0,:]
# same as x[0][0]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# index on x to return 9
x[0,2,2]


tensor(9)

In [ ]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

- Data in Numpy: --> PyTorch: -> `torch.from_numpy(ndarray)`
- Datt in Pytorch:--> Numpy:  -> `torch.tensor.numpy()`

In [ ]:
# numpy array to tensor:
import torch
import numpy as np

array = np.arange(1.,7.)
tensor = torch.from_numpy(array) # warning:
# it reflects default numpy datatype of float64.
# convert it to float32 if needed.

In [ ]:
array,tensor

(array([1., 2., 3., 4., 5., 6.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

In [ ]:
array.dtype
# by default the data type of numpy float is 64-bit


dtype('float64')

In [ ]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64))

In [ ]:
# different: so they dont share the same memory:

Tensor to Numpy array

In [ ]:
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype,numpy_tensor.dtype
# by default the numpy_array get assigned the default data type of tensor: float32.

(torch.float32, dtype('float32'))

## Reproducibility( random of random )

In [ ]:
# if we want to fix the numerals in the random data:
# create two random tensors:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
y = torch.rand(2,4)
torch.manual_seed(RANDOM_SEED)
z = torch.rand(2,4)
print(y==z)

tensor([[True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs(fast---- computing)

In [ ]:
!nvidia-smi

Mon Jun 19 13:08:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# check for GPU access with pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# counting the number of GPU
torch.cuda.device_count()

1

## Putting the tensors/ models on the GPU
- FASSSSSSSSST COMPUTING

In [ ]:
# create a tensor (default on cpu)
tensor = torch.tensor([3,3,4,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([3, 3, 4, 3]) cpu


In [ ]:
# Moving to GPU ( if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([3, 3, 4, 3], device='cuda:0')

# Moving tensors back on CPU

In [ ]:
tensor_on_gpu.numpy()
# if a tensor is on GPU, cna't transform it to NumPy.

TypeError: ignored

In [ ]:
# We first need to set the device to cpu:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([3, 3, 4, 3])

## Exercises and Extra-curricular:: Practice Module

00. PyTorch Fundamentals Exercises


2. Create a random tensor with shape (7, 7).

In [4]:
import torch
t1 = torch.rand(7,7)
t1

tensor([[0.2513, 0.6041, 0.9316, 0.8245, 0.6101, 0.7923, 0.7542],
        [0.0924, 0.8685, 0.0132, 0.3041, 0.4978, 0.3740, 0.5849],
        [0.1912, 0.2273, 0.2653, 0.2597, 0.4104, 0.4594, 0.8783],
        [0.9660, 0.1202, 0.5389, 0.0574, 0.6336, 0.2540, 0.6160],
        [0.2344, 0.0728, 0.4634, 0.1616, 0.8444, 0.9854, 0.0158],
        [0.7262, 0.7256, 0.1179, 0.7026, 0.6488, 0.2399, 0.1973],
        [0.9961, 0.4044, 0.9531, 0.0541, 0.3575, 0.8394, 0.0974]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [6]:
t2 = torch.rand(1,7)
# perform matrix multiplication:
t1.matmul(t2.T)

tensor([[1.5003],
        [0.9487],
        [0.9294],
        [0.8744],
        [0.5842],
        [0.8229],
        [0.9918]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [8]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
t1 = torch.rand(7,7)
t1


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [11]:
torch.manual_seed(RANDOM_SEED)
t2 = torch.rand(1,7)
# perform matrix multiplication:
t1.matmul(t2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [12]:
# set random seed on the GPU
SEED = 1234
torch.cuda.manual_seed(SEED)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

Device: cuda
```(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device="cuda:0"),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device="cuda:0"))```


In [15]:
# Set random seed
SEED = 1234
torch.manual_seed(SEED)
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
t1,t2
# Check for access to GPU

# Create two random tensors on GPU

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [16]:
# setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [19]:
# Moving to GPU ( if available)
device = "cuda"
t1_on_gpu = t1.to(device)
t2_on_gpu = t2.to(device)
t1_on_gpu,t2_on_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [22]:
#perform matmul on the two tensors.
t1_mat_t2 = t1_on_gpu.matmul(t2_on_gpu.T)
t1_mat_t2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.


In [25]:
# find max:
t1_mat_t2.max()

tensor(0.5617, device='cuda:0')

In [26]:
# find min
t1_mat_t2.min()

tensor(0.3647, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [28]:
# find arg max:
t1_mat_t2.argmax()

tensor(3, device='cuda:0')

In [30]:
# find arg min
t1_mat_t2.argmin().item()

0

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
SEED = 7
torch.manual_seed(SEED)
t3 = torch.rand(1,1,1,10)
t3

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [33]:
# REMOVE ALL SINGLE DIMENSIONS:
t3.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [35]:
t3.shape, t3.squeeze().shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))

 ## See the documentation on [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [torch.cuda.](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics)