what we will learn

- Modules and parameters
- Common NN Layer Types
- Other Layers & Functions

# Building Models in PyTorch

```torch.nn.Module``` and ```torch.nn.Parameter```

```Module``` class has models and model components like Neural Network
```Paramter``` class represents learning weights

In [1]:
import torch
class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel,self).__init__()
        
        self.linear1 = torch.nn.Linear(100,200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200,10)
        self.softmax = torch.nn.Softmax()
    
    def forward(self,x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.Linear2(x)
        x = self.softmax(x)
        return x
tinymodel = TinyModel()

In [2]:
print('The Model:')
print(tinymodel)

The Model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


In [5]:
print('Printing Just One Layer')
print(tinymodel.linear2)

Just One Layer
Linear(in_features=200, out_features=10, bias=True)


In [6]:
print('Model Parameters: ')
for param in tinymodel.parameters():
    print(param)

Model Parameters: 
Parameter containing:
tensor([[-0.0757,  0.0440, -0.0168,  ...,  0.0127,  0.0800, -0.0461],
        [-0.0476,  0.0791,  0.0863,  ...,  0.0366,  0.0125, -0.0045],
        [ 0.0909,  0.0542,  0.0709,  ..., -0.0813,  0.0178, -0.0331],
        ...,
        [ 0.0622, -0.0067, -0.0510,  ...,  0.0347,  0.0845,  0.0128],
        [ 0.0105, -0.0284,  0.0792,  ...,  0.0231,  0.0826, -0.0921],
        [ 0.0235,  0.0383,  0.0977,  ..., -0.0747,  0.0094, -0.0377]],
       requires_grad=True)
Parameter containing:
tensor([ 4.7380e-04,  4.2523e-03,  7.4618e-03, -2.7857e-02,  7.8912e-02,
        -6.4051e-03,  8.0970e-02,  1.1533e-02, -3.9098e-02, -9.8823e-02,
        -3.8040e-02, -4.6897e-02, -8.4200e-02, -2.8356e-02,  2.3005e-02,
        -4.8916e-02, -6.7992e-02, -7.7021e-02,  7.3736e-02, -4.6852e-02,
         3.6273e-02, -9.5378e-02,  9.3080e-02, -2.2082e-02, -2.1576e-02,
         2.1133e-02, -7.7074e-02,  2.9136e-02,  7.9210e-02, -3.0213e-02,
         5.3316e-02, -1.3063e-03, -6.0

In [7]:
print('Layer Parameters:\n')
for param in tinymodel.linear2.parameters():
    print(param)

Layer Parameters:

Parameter containing:
tensor([[-0.0371,  0.0567,  0.0383,  ..., -0.0611,  0.0523,  0.0086],
        [-0.0207,  0.0235, -0.0170,  ..., -0.0545, -0.0412, -0.0467],
        [ 0.0465, -0.0206,  0.0619,  ..., -0.0688,  0.0641,  0.0080],
        ...,
        [ 0.0476,  0.0465,  0.0403,  ..., -0.0286, -0.0009, -0.0605],
        [-0.0625,  0.0260,  0.0554,  ...,  0.0576, -0.0618, -0.0696],
        [ 0.0472,  0.0705, -0.0359,  ...,  0.0490, -0.0323, -0.0622]],
       requires_grad=True)
Parameter containing:
tensor([-0.0339, -0.0110,  0.0691,  0.0521, -0.0226,  0.0538,  0.0370, -0.0321,
        -0.0693,  0.0454], requires_grad=True)


In [8]:
# it prints ins and out weights of the linear2 layer.

# Common Layer Types

# Linear Layers

Every input layer connected to every output layers.
Thus affecting each of the output.

In [13]:
lin = torch.nn.Linear(3,2) # 3-input, 2-output layer.
x = torch.rand(1,3) # 1*3 --> of random values.
print('Input:')
print(x)

Input:
tensor([[0.6840, 0.0503, 0.9075]])


In [14]:
print('weight and Bias parameters')
for param in lin.parameters():
    print(param)

weight and Bias parameters
Parameter containing:
tensor([[-0.3171, -0.3069,  0.1067],
        [-0.5759,  0.2002,  0.1832]], requires_grad=True)
Parameter containing:
tensor([0.0867, 0.2479], requires_grad=True)


In [27]:
y = lin(x) # it multiplies the weights(2*3) with the input(3*1)->x.
print('Output')
print(y)


Output
tensor([[-0.0488,  0.0304]], grad_fn=<AddmmBackward0>)


In [30]:
# if we multiply the x with the linear weights and add the bias, we will get the same output y.

# CNN


# Max Pooling

It reduces a tensor by combining cells and assigning max or min of those cells.


In [31]:
my_tensor = torch.rand(1,6,6) # one 6*6 tensors.
print(my_tensor)

tensor([[[0.8656, 0.4047, 0.5848, 0.3218, 0.1115, 0.9315],
         [0.1740, 0.8545, 0.3935, 0.0481, 0.3267, 0.4074],
         [0.0430, 0.2620, 0.1754, 0.4877, 0.3150, 0.1291],
         [0.0735, 0.5430, 0.7867, 0.8467, 0.9925, 0.3077],
         [0.4777, 0.4683, 0.6194, 0.9308, 0.5748, 0.7355],
         [0.7159, 0.9725, 0.2672, 0.6016, 0.5797, 0.9818]]])


In [33]:
maxpool_layer = torch.nn.MaxPool2d(3) # 3*3 filter.
print(maxpool_layer(my_tensor))

tensor([[[0.8656, 0.9315],
         [0.9725, 0.9925]]])


# Normalization layer

It re-center and normalize the output of one layer before feeding it to another.
Centering an scaling the imediate tensor has a number of beneficial effects, such as
getting rid of 
- exploding/vanishing gradients

In [34]:
my_tensor = torch.rand(1,4,4)
print(my_tensor)
print(my_tensor.mean())


tensor([[[0.3290, 0.0494, 0.4725, 0.9789],
         [0.4204, 0.5078, 0.9075, 0.3936],
         [0.9825, 0.9825, 0.3947, 0.3126],
         [0.7614, 0.9850, 0.9879, 0.2727]]])
tensor(0.6087)


In [41]:
norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)
print(normed_tensor.mean())

tensor([[[-0.3810, -1.2096,  0.0447,  1.5458],
         [-0.6629, -0.2397,  1.6953, -0.7926],
         [ 0.9957,  0.9957, -0.8657, -1.1258],
         [ 0.0329,  0.8003,  0.8103, -1.6436]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(-4.4703e-08, grad_fn=<MeanBackward0>)


In [42]:
normed_tensor.mean()

tensor(-4.4703e-08, grad_fn=<MeanBackward0>)

# Dropout layer

Randomly selecting parts of the input layer during training.

In [75]:
my_tensor = torch.rand(1,4,4)
print(my_tensor)
dropout = torch.nn.Dropout(p = 0.4)

tensor([[[0.5837, 0.0683, 0.5531, 0.1268],
         [0.9616, 0.4444, 0.4141, 0.7573],
         [0.2990, 0.0194, 0.9566, 0.9972],
         [0.2015, 0.0215, 0.4950, 0.7430]]])


In [76]:
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.0000, 0.1139, 0.9219, 0.0000],
         [1.6026, 0.7407, 0.0000, 1.2622],
         [0.0000, 0.0323, 0.0000, 1.6619],
         [0.3359, 0.0359, 0.8250, 1.2383]]])
tensor([[[0.9729, 0.1139, 0.9219, 0.2114],
         [1.6026, 0.7407, 0.0000, 0.0000],
         [0.4984, 0.0323, 1.5943, 0.0000],
         [0.3359, 0.0359, 0.8250, 1.2383]]])


In [77]:
# when we put the tensor elements in the dropout twice: 
# in both cases the random indexed elements are droppout.
# also the non-values are indentical

if we simply write ```dropout()``` it will take ```p=0.5```

# Activation functions


# Loss functions 

# RNN
# Transformer