# Pytorch 

### Tensors Basics

A tensor is a generalization of vectors and matrices and is easily understood as a
multidimensional array. It is a term and set of techniques known in machine learning in th training
and operation of deep learning models can be described in terms of tensors. In many cases tensors are used
as replacement of NumPy to use the power of GPUs.


Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can 
calculate arithmetic operation with tensors.

In [2]:
pip install torchvision

     ---------------------------------------- 1.2/1.2 MB 6.3 MB/s eta 0:00:00
     -------------------------------------- 172.3/172.3 MB 5.3 MB/s eta 0:00:00
     ---------------------------------------- 5.7/5.7 MB 5.3 MB/s eta 0:00:00
     ---------------------------------------- 2.1/2.1 MB 5.5 MB/s eta 0:00:00
     -------------------------------------- 536.2/536.2 kB 5.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

In [4]:
torch.__version__

'2.0.1+cpu'

In [5]:
import numpy as np

In [32]:
# created list of integers
lst = [3,4,43,2]

In [33]:
# converting list to numpy array.
arr  = np.array(lst)

In [34]:
arr

array([ 3,  4, 43,  2])

# Convert Numpy to Pytorch Tensors

In [35]:
tensors = torch.from_numpy(arr)

In [36]:
tensors

tensor([ 3,  4, 43,  2], dtype=torch.int32)

In [37]:
# indexing similar to numpy
tensors[2]

tensor(43, dtype=torch.int32)

In [38]:
tensors[1:3]

tensor([ 4, 43], dtype=torch.int32)

In [39]:
tensors[:3]

tensor([ 3,  4, 43], dtype=torch.int32)

In [42]:
# disadvantage of tesors: memory allocation was same for array and tensors
# so it will overwrite the value in both the data structures.
tensors[3] = 3222

In [43]:
arr[3]

3222

In [44]:
# so we better use torch.tensor(arr) to prevent this
# it basically makes a copy of array and work on it.

In [45]:
tensor_arr = torch.tensor(arr)

In [46]:
tensor_arr

tensor([   3,    4,   43, 3222], dtype=torch.int32)

In [48]:
tensor_arr[3]  = 1000

In [49]:
arr[3]

3222

In [50]:
# no change in array:

# Zeros and Ones

In [61]:
# using inbuilt-function and specifying the dtype.
torch.zeros(3,4,dtype=torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [63]:
torch_ones = torch.ones(2,4,dtype=torch.float32)

In [64]:
torch_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# 2-D array

In [73]:
# 2d numpy array (0--15) reshaped to 5*3
np_2d = np.arange(0,15).reshape(5,3)

In [74]:
np_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [75]:
# converting to torch data
torch_2d = torch.tensor(np_2d)

In [76]:
torch_2d

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [82]:
# performing indexing in the 2d-torch object
torch_2d[1][2]

tensor(5, dtype=torch.int32)

In [90]:
# 1st row
torch_2d[:][1]

tensor([3, 4, 5], dtype=torch.int32)

In [96]:
# 2nd column
torch_2d[:,2]

tensor([ 2,  5,  8, 11, 14], dtype=torch.int32)

In [97]:
# upto 2nd row 
torch_2d[:2]

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

# arithmetic operations with torch datas.

In [98]:
a = torch.tensor([3,2,42],dtype=torch.float)
b = torch.tensor([9,2,4],dtype=torch.float) 

In [102]:
a+b

tensor([12.,  4., 46.])

In [103]:
#using torch inbuilt-function .add()
torch.add(a,b)

tensor([12.,  4., 46.])

In [109]:
# now storing it in c-having same data type as a,b
c = torch.zeros(3) #all initially 0.

In [111]:
c = torch.add(a,b,out=c) # out = c --> means c as it was initialized

In [112]:
c

tensor([12.,  4., 46.])

In [113]:
# using .sum() operation to add all the output of the tensor-array
c.sum() 

tensor(62.)

# dot product and multiplication operation

In [119]:
x = torch.tensor([3,3,2],dtype=torch.float)
y = torch.tensor([5,3,2],dtype=torch.float)

In [120]:
x.mul(y)

tensor([15.,  9.,  4.])

In [121]:
# dot product
x.dot(y) # sum of all(x*y)

tensor(28.)

# matrix multiplication

In [122]:
x= torch.tensor([[3,3,2],[33,24,2]],dtype=torch.float)
y= torch.tensor([[2,3],[2,4],[5,3]],dtype=torch.float)

In [125]:
x.matmul(y)
# or--> torch.matmul(x,y)

tensor([[ 22.,  27.],
        [124., 201.]])

In [126]:
# or mm
torch.mm(x,y)

tensor([[ 22.,  27.],
        [124., 201.]])

In [128]:
# or x@y.
x@y

tensor([[ 22.,  27.],
        [124., 201.]])