# Creating tensors

simplest way to create tensors is ```torch.empty()``` function call:

In [3]:
import torch

In [4]:
x = torch.empty(2,3)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-2.9028e-33,  7.3428e-43, -2.9028e-33],
        [ 7.3428e-43, -2.8765e-33,  7.3428e-43]])


What we did just now
- Torch.empty() doesnot initialize x with any values. They are just random memory allocation
- 1-D tensor is vector
- 2-D tensor is matrix and rest simply called tensor

In [8]:
zeros = torch.zeros(3,4)
print(zeros)
ones = torch.ones(3,2)
print(ones)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
torch.manual_seed(123) # same as random state: to prevent rand() function from changing values after each iteration.
random=torch.rand(2,3)
print(random)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


In [17]:
# While performing tensors operation: the shape must be taken care of

In [53]:
x = torch.empty(2,2,3)
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


Tensor Data Types 
==

In [60]:
# setting the data-type in advance
a = torch.ones((3,2),dtype=torch.int16)
print(a)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [62]:
b = torch.rand((3,3),dtype=torch.float32)*23
print(b)

tensor([[ 9.2400,  2.7271, 19.0301],
        [ 8.7879, 15.1914, 19.6322],
        [13.6425, 14.6447, 22.6005]])


In [63]:
# converting the above b data-type to 32-bit integer
c = b.to(torch.int32)
print(c) # gives the integer value of the data.

tensor([[ 9,  2, 19],
        [ 8, 15, 19],
        [13, 14, 22]], dtype=torch.int32)


Available datatypes are:

```torch.bool ```
```torch.int8 ```
```torch.int32 ```
```torch.int64 ```
```torch.float ```
```torch.double ```
```torch.bfloat ```
```torch.half ```
```torch.uint8 ```

# Maths and & logic with pytorhc tensors

In [68]:
ones = torch.zeros(3,4)+1
print(ones)
twos = torch.ones(3,2)+1
print(twos)
threes = torch.ones(3,2)*3
print(threes)
sqrt2s = twos**0.5
print(sqrt2s)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142],
        [1.4142, 1.4142]])


# Exponents-matrix

In [71]:
powers2 = twos**(torch.tensor([[0,1],[3,5],[2,4]]))
print(powers2)

tensor([[ 1.,  2.],
        [ 8., 32.],
        [ 4., 16.]])


In [72]:
# In matrix multiplication the shape of the matrices must be taken care of

# Tensor Broadcasting

Multiplying ```2*4 matrix with 1*4 matrix```:

In [73]:
rand = torch.rand(2,4)
doubled = rand*(torch.ones(1,4)*10)
print(rand)
print(doubled)

tensor([[0.2745, 0.6584, 0.2775, 0.8573],
        [0.8993, 0.0390, 0.9268, 0.7388]])
tensor([[2.7450, 6.5838, 2.7754, 8.5732],
        [8.9933, 0.3901, 9.2682, 7.3876]])


### each row of the rand matrix is multiplied by the row matrix of doubled.
### rules of tensor broadcasting:
1. One of the dimensions must of of size 1
2. Similar sized matrix
3. Dimension doesnot exist in one of the tensors

# More Math With Tensors

In [81]:
import math

In [79]:
# common functions
a = torch.rand(2,4)*5-1
print('Common functions: ')
print('abs',torch.abs(a),'\n')
print('ceil',torch.ceil(a),'\n')
print('torch',torch.floor(a),'\n')
print(torch.clamp(a,-0.5,0.5))
# the .clamp(),value less than min replaced by min, and greter than max--> max 

Common functions: 
abs tensor([[0.5043, 1.6003, 0.9169, 1.2253],
        [0.9372, 2.6707, 3.6944, 3.0281]]) 

ceil tensor([[1., 2., 1., 2.],
        [-0., 3., 4., 4.]]) 

torch tensor([[ 0.,  1.,  0.,  1.],
        [-1.,  2.,  3.,  3.]]) 

tensor([[ 0.5000,  0.5000,  0.5000,  0.5000],
        [-0.5000,  0.5000,  0.5000,  0.5000]])


In [82]:
# trigonometric functions
angles = torch.tensor([0,math.pi/4,math.pi/2,3*math.pi/4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSines and arcsine:')
print(angles)
print(sines)
print(inverses)


Sines and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])


In [83]:
# Bit wise operations
print('\nbitwise XOR:')
b = torch.tensor([1,5,13])
c = torch.tensor([4,32,4])
print(torch.bitwise_xor(b,c))


bitwise XOR:
tensor([ 5, 37,  9])


In [96]:
# Reduction operations
print('\nReduction ops:')
print(torch.max(b))
d = torch.tensor([[3.,4.,3.],[234.,4.3,2.],[2.,3.,4.]])
print(torch.max(d).item())
# print(torch.mean(b))
# print(torch.std(b))
print(torch.prod(b)) # product of all numbers
print(torch.unique(torch.tensor([2,2,4,3,1,4,5]))) # filter unique valeus


Reduction ops:
tensor(13)
234.0
tensor(65)
tensor([1, 2, 3, 4, 5])


# 4.altering tensors in place.

# 5. copying tensors

# 6.Moving to GPU

# 7. Manipulating Tensor Shapes

In [100]:
# sometimes we need to change the shape of  tensor.

### changing the number of dimensions

In [102]:
a = torch.rand(3,226,226) # a 226-pixel square with 3-color channels
b = a.unsqueeze(0) # adds a new 0 the column-batch of one elment of 226*226 pixel having 3 colors.
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


### squeeze

In [104]:
a = torch.rand(1,10)
print(a.shape)
print(a)

torch.Size([1, 10])
tensor([[0.6056, 0.3244, 0.9140, 0.7369, 0.7267, 0.6998, 0.5229, 0.4763, 0.2782,
         0.6759]])


In [106]:
# we see that a is 2-d tensor: [[]]->1*20
b = a.squeeze(0) # squeeze makes it 1-d tensor: ie. matrix---> vector
print(b.shape)
print(b)

torch.Size([10])
tensor([0.6056, 0.3244, 0.9140, 0.7369, 0.7267, 0.6998, 0.5229, 0.4763, 0.2782,
        0.6759])


In [110]:
c = torch.rand(2,2)
print(c.shape)

torch.Size([2, 2])


In [113]:
d = c.squeeze(0)
print(d.shape)

torch.Size([2, 2])


``` No change in the dimension is seen ```

So the ``` squeeze(), unsqeeeze() ``` works only with dimension of one.

In [114]:
#

The ```squeeze()``` and ```unsqueeze()``` methods also have the in-place versions, ```squeeze_()``` and ```unsqueeze()```:`

In [119]:
#changing the shape in-place without creating a copy of the tensor
batch_me = torch.rand(3,222,222)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 222, 222])
torch.Size([1, 3, 222, 222])


 - Numpy Bridge: numpy <--> tensor

In [127]:
import numpy as np
numpy_array=np.ones((2,3)) # 2-d array
print(numpy_array)
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [128]:
# other way

In [129]:
pytorch_rand=torch.rand(2,3)
print(pytorch_rand)
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5283, 0.2906, 0.1328],
        [0.5763, 0.2216, 0.5283]])
[[0.5283123  0.29061335 0.13281071]
 [0.5763394  0.22155994 0.5282548 ]]


##### These converted objects are using the same underlying memory as their source objects, meaning the change in one will affect the other